/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horarioclases.gui;

/**
 *
 * @author Luis
 */
public class NuevoHorario extends javax.swing.JFrame {

    /**
     * Creates new form NuevoHorario
     */
    public NuevoHorario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarra = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        pblNavegacion = new javax.swing.JPanel();
        btnHorario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnProfesor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnExpEdu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnSalon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlhorario = new javax.swing.JPanel();
        lblCrearHorario = new javax.swing.JLabel();
        lblFolioHorario = new javax.swing.JLabel();
        txtFolioHorario = new javax.swing.JTextField();
        lblGrupoHorario = new javax.swing.JLabel();
        txtGrupoHorario = new javax.swing.JTextField();
        lblProgEdu = new javax.swing.JLabel();
        txtProgEdu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblAulaHorario = new javax.swing.JLabel();
        txtAulaHorario = new javax.swing.JTextField();
        btnAgregarExp = new javax.swing.JButton();
        btnAgregarExp1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocationByPlatform(true);
        setResizable(false);

        pnlBarra.setBackground(new java.awt.Color(255, 255, 255));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N

        javax.swing.GroupLayout pnlBarraLayout = new javax.swing.GroupLayout(pnlBarra);
        pnlBarra.setLayout(pnlBarraLayout);
        pnlBarraLayout.setHorizontalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCerrar)
                .addContainerGap())
        );
        pnlBarraLayout.setVerticalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pblNavegacion.setBackground(new java.awt.Color(24, 82, 157));
        pblNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHorario.setBackground(new java.awt.Color(24, 82, 157));
        btnHorario.setPreferredSize(new java.awt.Dimension(26, 48));
        btnHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHorarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHorarioMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendarblack.png"))); // NOI18N

        javax.swing.GroupLayout btnHorarioLayout = new javax.swing.GroupLayout(btnHorario);
        btnHorario.setLayout(btnHorarioLayout);
        btnHorarioLayout.setHorizontalGroup(
            btnHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHorarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnHorarioLayout.setVerticalGroup(
            btnHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHorarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pblNavegacion.add(btnHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, 70));

        btnProfesor.setBackground(new java.awt.Color(24, 82, 157));
        btnProfesor.setPreferredSize(new java.awt.Dimension(26, 48));
        btnProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfesorMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendarblack.png"))); // NOI18N

        javax.swing.GroupLayout btnProfesorLayout = new javax.swing.GroupLayout(btnProfesor);
        btnProfesor.setLayout(btnProfesorLayout);
        btnProfesorLayout.setHorizontalGroup(
            btnProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnProfesorLayout.setVerticalGroup(
            btnProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfesorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pblNavegacion.add(btnProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 80, 70));

        btnExpEdu.setBackground(new java.awt.Color(24, 82, 157));
        btnExpEdu.setPreferredSize(new java.awt.Dimension(26, 48));
        btnExpEdu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExpEduMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExpEduMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendarblack.png"))); // NOI18N

        javax.swing.GroupLayout btnExpEduLayout = new javax.swing.GroupLayout(btnExpEdu);
        btnExpEdu.setLayout(btnExpEduLayout);
        btnExpEduLayout.setHorizontalGroup(
            btnExpEduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExpEduLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnExpEduLayout.setVerticalGroup(
            btnExpEduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExpEduLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pblNavegacion.add(btnExpEdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 80, 70));

        btnSalon.setBackground(new java.awt.Color(24, 82, 157));
        btnSalon.setPreferredSize(new java.awt.Dimension(26, 48));
        btnSalon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalonMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendarblack.png"))); // NOI18N

        javax.swing.GroupLayout btnSalonLayout = new javax.swing.GroupLayout(btnSalon);
        btnSalon.setLayout(btnSalonLayout);
        btnSalonLayout.setHorizontalGroup(
            btnSalonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnSalonLayout.setVerticalGroup(
            btnSalonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pblNavegacion.add(btnSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 80, 70));

        pnlhorario.setBackground(new java.awt.Color(255, 255, 255));
        pnlhorario.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 48)); // NOI18N

        lblCrearHorario.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lblCrearHorario.setText("Crear horario");

        lblFolioHorario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblFolioHorario.setText("Folio:");

        txtFolioHorario.setEditable(false);
        txtFolioHorario.setBackground(new java.awt.Color(255, 255, 255));
        txtFolioHorario.setBorder(null);

        lblGrupoHorario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblGrupoHorario.setText("Grupo:");

        txtGrupoHorario.setEditable(false);
        txtGrupoHorario.setBackground(new java.awt.Color(255, 255, 255));
        txtGrupoHorario.setBorder(null);

        lblProgEdu.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblProgEdu.setText("Programa Educativo:");

        txtProgEdu.setEditable(false);
        txtProgEdu.setBackground(new java.awt.Color(255, 255, 255));
        txtProgEdu.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Experiencia Educativa", "NRC", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblAulaHorario.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblAulaHorario.setText("Aula:");

        txtAulaHorario.setEditable(false);
        txtAulaHorario.setBackground(new java.awt.Color(255, 255, 255));
        txtAulaHorario.setBorder(null);

        btnAgregarExp.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarExp.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnAgregarExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnAgregarExp.setText("Agregar Experiencia Educativa");
        btnAgregarExp.setActionCommand("  Agregar Experiencia Educativa");
        btnAgregarExp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAgregarExp.setBorderPainted(false);
        btnAgregarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExpActionPerformed(evt);
            }
        });

        btnAgregarExp1.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarExp1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnAgregarExp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        btnAgregarExp1.setText("Eliminar Experiencia Educativa");
        btnAgregarExp1.setActionCommand("  Agregar Experiencia Educativa");
        btnAgregarExp1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAgregarExp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlhorarioLayout = new javax.swing.GroupLayout(pnlhorario);
        pnlhorario.setLayout(pnlhorarioLayout);
        pnlhorarioLayout.setHorizontalGroup(
            pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhorarioLayout.createSequentialGroup()
                .addGroup(pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlhorarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlhorarioLayout.createSequentialGroup()
                                .addComponent(lblFolioHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFolioHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlhorarioLayout.createSequentialGroup()
                                .addComponent(lblGrupoHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGrupoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlhorarioLayout.createSequentialGroup()
                                .addComponent(lblProgEdu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProgEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAulaHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAulaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCrearHorario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlhorarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(pnlhorarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btnAgregarExp1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        pnlhorarioLayout.setVerticalGroup(
            pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhorarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCrearHorario)
                .addGap(22, 22, 22)
                .addGroup(pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFolioHorario)
                    .addComponent(txtFolioHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupoHorario)
                    .addComponent(txtGrupoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgEdu)
                    .addComponent(txtProgEdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAulaHorario)
                    .addComponent(txtAulaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlhorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarExp1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pblNavegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlhorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlhorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pblNavegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHorarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHorarioMouseEntered
        btnHorario.setBackground(new java.awt.Color(24, 82, 190));
    }//GEN-LAST:event_btnHorarioMouseEntered

    private void btnHorarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHorarioMouseExited
        btnHorario.setBackground(new java.awt.Color(24, 82, 157));
    }//GEN-LAST:event_btnHorarioMouseExited

    private void btnProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesorMouseEntered
        btnProfesor.setBackground(new java.awt.Color(24, 82, 190));
    }//GEN-LAST:event_btnProfesorMouseEntered

    private void btnProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesorMouseExited
        btnProfesor.setBackground(new java.awt.Color(24, 82, 157));
    }//GEN-LAST:event_btnProfesorMouseExited

    private void btnExpEduMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpEduMouseEntered
        btnExpEdu.setBackground(new java.awt.Color(24, 82, 190));
    }//GEN-LAST:event_btnExpEduMouseEntered

    private void btnExpEduMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpEduMouseExited
        btnExpEdu.setBackground(new java.awt.Color(24, 82, 157));
    }//GEN-LAST:event_btnExpEduMouseExited

    private void btnSalonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalonMouseEntered
        btnSalon.setBackground(new java.awt.Color(24, 82, 190));
    }//GEN-LAST:event_btnSalonMouseEntered

    private void btnSalonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalonMouseExited
        btnSalon.setBackground(new java.awt.Color(24, 82, 157));
    }//GEN-LAST:event_btnSalonMouseExited

    private void btnAgregarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarExpActionPerformed

    private void btnAgregarExp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarExp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NuevoHorario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarExp;
    private javax.swing.JButton btnAgregarExp1;
    private javax.swing.JPanel btnExpEdu;
    private javax.swing.JPanel btnHorario;
    private javax.swing.JPanel btnProfesor;
    private javax.swing.JPanel btnSalon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAulaHorario;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCrearHorario;
    private javax.swing.JLabel lblFolioHorario;
    private javax.swing.JLabel lblGrupoHorario;
    private javax.swing.JLabel lblProgEdu;
    private javax.swing.JPanel pblNavegacion;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlhorario;
    private javax.swing.JTextField txtAulaHorario;
    private javax.swing.JTextField txtFolioHorario;
    private javax.swing.JTextField txtGrupoHorario;
    private javax.swing.JTextField txtProgEdu;
    // End of variables declaration//GEN-END:variables
}
